
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - gateway.kusk.io
  resources:
  - envoyfleet
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.kusk.io
  resources:
  - envoyfleet/finalizers
  verbs:
  - update
- apiGroups:
  - gateway.kusk.io
  resources:
  - envoyfleet/status
  verbs:
  - get
  - patch
  - update
