version: "3.7"
services:

  front-envoy:
    container_name: front-envoy
    image: envoyproxy/envoy-dev:latest
    networks:
      kusk-gateway:
        ipv4_address: "172.21.0.2"
    volumes:
    - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
    - "8080:8080"
    depends_on:
    - petstore
    - go-control-plane
  petstore:
    container_name: petstore
    image: swaggerapi/petstore3:unstable
    networks:
      kusk-gateway:
        ipv4_address: "172.21.0.3"
  go-control-plane:
    container_name: go-control-plane
    build:
      context: .
      dockerfile: Dockerfile-control-plane
    healthcheck:
      test: nc -zv localhost 18000
    networks:
      kusk-gateway:
        ipv4_address: "172.21.0.4"


networks:
  kusk-gateway:
    name: "kusk-gateway"
    ipam:
      driver: default
      config:
      - subnet: 172.21.0.0/24
